--1

-- SELECT EXTRACT (YEAR FROM COL_DATE), COUNT(*) 
-- FROM CASE
-- GROUP BY EXTRACT (YEAR FROM COL_DATE)


--2

--SELECT VE_MAKE, COUNT(*) AS N_COLLISION
--FROM (VEHICLE INNER JOIN PARTY_INVOLVE ON VEHICLE.VE_NUM = PARTY_INVOLVE.VE_NUM)
--GROUP BY VE_MAKE
--ORDER BY N_COLLISION DESC
--FETCH FIRST 1 ROWS ONLY


--3

--SELECT NOM/(SELECT COUNT(*) FROM CASE)
--FROM
--    (SELECT COUNT(*) AS NOM
--    FROM CASE
--    WHERE CASE.LIGHTING LIKE '%dark%')
    

--4

--SELECT COUNT(*) 
--FROM WEATHER
--WHERE WEATHER_CON LIKE '%SNOWING%'


--5

--SELECT TO_CHAR(COL_DATE, 'D') AS WEEK_DAY, COUNT(*) AS N_COLLISONS
--FROM CASE
--GROUP BY TO_CHAR(COL_DATE, 'D')
--ORDER BY N_COLLISONS DESC
--FETCH FIRST 1 ROWS ONLY


--6

--SELECT WEATHER_CON, COUNT(*) AS N_COLLISION
--FROM WEATHER
--GROUP BY WEATHER_CON
--ORDER BY N_COLLISION


--7

--SELECT COUNT(*) AS N_PARTIES 
--FROM PARTY_INVOLVE P, ROAD_CON R
--WHERE P.CASE_ID = R.CASE_ID AND P.AT_FAULT = 1 AND P.FIN_RESP = 'Y' AND R.ROAD_CON LIKE '%loose material%'


-- 8 








    
